public class DW_MetadataDTO {
    
    public class QualifyingQuestionsPageDTO {
        public String PreviousStepURL;
        
        public String NextStepURL;
        
        public String CancelStepURL;
        
        public Map<String, String> MajorFocusMap;
        
        public Map<String, String> OrganSiteMap;
        
        public Map<String, String> PrimaryResearchAreaMap;
        
        public Map<String, String> SpecificResearchAreaMap;
        
        public Map<String, String> AdditionalResearchAreaMap;
        
        public Map<String, String> AcademicDegreeMap;
    }
}